package com.learningassistant.quiz.dto;

import java.util.List;

/**
 * Representation of a question generated by the Python AI service.
 */
public record GeneratedQuestion(
        String question,
        List<String> options,
        String correct_answer
) {
}

